### ISSUE TITLE
result list

### ISSUE THREAD

**Issue by vokarl** [vokarl/capstone#11]
## Value Proposition

**As a user** 
**I want to see the result list**   
**so that I can see and use the collected data** 
​

## Description

![Image](https://user-images.githubusercontent.com/131611235/251082346-6f3780c4-df9e-4f3b-aa27-8e3f7c1b004a.png)

​

## Acceptance Criteria

- [ ] the result list shows a simple collection of all piles and every tree in the corresponding 
       quality category.
- [ ] the list is scrollable

      ​

## Tasks

- [ ] create a new branch "result list" and switch to it
- [ ] create a new dummy result page

      ​

**Comment by matschi3** [comment]
i have no idea of trees and stuff , but the UserStory looks good 👍🏼
