### ISSUE TITLE
decide tree species

### ISSUE THREAD

**Issue by vokarl** [vokarl/capstone#2]
## Value Proposition

**As a user** 
**I want to see all the tree species**  
**so that I can choose the tree species I want to sort** 
​

## Description

![Image](https://github.com/vokarl/journal/assets/131611235/60a4178c-be47-415e-9c93-63e28db8542f)

​

## Acceptance Criteria

- [ ] trees as list items
- [ ] heading scrolls with the list
- [ ] list scrolls vertically 

      ​

## Tasks

- [ ] create a branch
- [ ] create an array for the tree list
- [ ] add an hardcoded heading 
- [ ] map the tree list
- [ ] render the list 

      ​
