### ISSUE TITLE
sorting criteria oak

### ISSUE THREAD

**Issue by vokarl** [vokarl/capstone#4]
## Value Proposition

**As a user**  
**I want to see the sorting criteria for the oak log** 
**so that I can start the sorting process** 
​

## Description

![Image](https://github.com/vokarl/journal/assets/131611235/783d0764-dc23-4d4a-b921-f9b3effa6109)

...
​

## Acceptance Criteria

- [ ] heading is fixed
- [ ] list scrolls vertically
- [ ] criteria as list item
- [ ] back button position is fixed
      ​

## Tasks

- [ ] create a branch
- [ ] create an array for all possible sorting criteria
- [ ] add the heading and make ist fixed
- [ ] map the list of criteria 
- [ ] render the list
- [ ] create a button that leads back to the tree list page
- [ ] make the button fixed
      ​

**Comment by matschi3** [comment]
LGTM 🚀
keep going! ✌🏼
